services:
  # --- DATABÁZA ---
  postgres-db:
    image: postgres:16-alpine
    container_name: autolog_postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - "${POSTGRES_DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_DB_USER} -d ${POSTGRES_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- BACKEND ---
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autolog_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/${POSTGRES_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_DB_PASSWORD}
      FRONTEND_URL: http://localhost:3000
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      postgres-db:
        condition: service_healthy
    restart: always

volumes:
  postgres_data: