spring.application.name=DigitalServiceBook
server.port=8080

# Vytvorí súbor s názvom data.db v priecinku tvojho projektu
spring.datasource.url=jdbc:sqlite:database/data.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Povie Hibernate-u, ako sa má bavis so SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true